// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: External/proto/Bowerbird.proto

package bowerbird.gpb;

public final class BowerbirdMessageProtocolGPB {
  private BowerbirdMessageProtocolGPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ItemFieldOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string ident = 1;
    /**
     * <code>required string ident = 1;</code>
     */
    boolean hasIdent();
    /**
     * <code>required string ident = 1;</code>
     */
    java.lang.String getIdent();
    /**
     * <code>required string ident = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdentBytes();

    // required string fieldName = 2;
    /**
     * <code>required string fieldName = 2;</code>
     */
    boolean hasFieldName();
    /**
     * <code>required string fieldName = 2;</code>
     */
    java.lang.String getFieldName();
    /**
     * <code>required string fieldName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFieldNameBytes();

    // optional bool required = 3;
    /**
     * <code>optional bool required = 3;</code>
     */
    boolean hasRequired();
    /**
     * <code>optional bool required = 3;</code>
     */
    boolean getRequired();
  }
  /**
   * Protobuf type {@code bowerbird.ItemField}
   */
  public static final class ItemField extends
      com.google.protobuf.GeneratedMessage
      implements ItemFieldOrBuilder {
    // Use ItemField.newBuilder() to construct.
    private ItemField(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ItemField(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ItemField defaultInstance;
    public static ItemField getDefaultInstance() {
      return defaultInstance;
    }

    public ItemField getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ItemField(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              ident_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              fieldName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              required_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bowerbird.gpb.BowerbirdMessageProtocolGPB.internal_static_bowerbird_ItemField_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bowerbird.gpb.BowerbirdMessageProtocolGPB.internal_static_bowerbird_ItemField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.class, bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.Builder.class);
    }

    public static com.google.protobuf.Parser<ItemField> PARSER =
        new com.google.protobuf.AbstractParser<ItemField>() {
      public ItemField parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemField(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ItemField> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string ident = 1;
    public static final int IDENT_FIELD_NUMBER = 1;
    private java.lang.Object ident_;
    /**
     * <code>required string ident = 1;</code>
     */
    public boolean hasIdent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ident = 1;</code>
     */
    public java.lang.String getIdent() {
      java.lang.Object ref = ident_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ident_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ident = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdentBytes() {
      java.lang.Object ref = ident_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ident_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string fieldName = 2;
    public static final int FIELDNAME_FIELD_NUMBER = 2;
    private java.lang.Object fieldName_;
    /**
     * <code>required string fieldName = 2;</code>
     */
    public boolean hasFieldName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string fieldName = 2;</code>
     */
    public java.lang.String getFieldName() {
      java.lang.Object ref = fieldName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fieldName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fieldName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFieldNameBytes() {
      java.lang.Object ref = fieldName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool required = 3;
    public static final int REQUIRED_FIELD_NUMBER = 3;
    private boolean required_;
    /**
     * <code>optional bool required = 3;</code>
     */
    public boolean hasRequired() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool required = 3;</code>
     */
    public boolean getRequired() {
      return required_;
    }

    private void initFields() {
      ident_ = "";
      fieldName_ = "";
      required_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIdent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFieldName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFieldNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, required_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFieldNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, required_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bowerbird.ItemField}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemFieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bowerbird.gpb.BowerbirdMessageProtocolGPB.internal_static_bowerbird_ItemField_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bowerbird.gpb.BowerbirdMessageProtocolGPB.internal_static_bowerbird_ItemField_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.class, bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.Builder.class);
      }

      // Construct using bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ident_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fieldName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        required_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bowerbird.gpb.BowerbirdMessageProtocolGPB.internal_static_bowerbird_ItemField_descriptor;
      }

      public bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField getDefaultInstanceForType() {
        return bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.getDefaultInstance();
      }

      public bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField build() {
        bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField buildPartial() {
        bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField result = new bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ident_ = ident_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fieldName_ = fieldName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.required_ = required_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField) {
          return mergeFrom((bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField other) {
        if (other == bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.getDefaultInstance()) return this;
        if (other.hasIdent()) {
          bitField0_ |= 0x00000001;
          ident_ = other.ident_;
          onChanged();
        }
        if (other.hasFieldName()) {
          bitField0_ |= 0x00000002;
          fieldName_ = other.fieldName_;
          onChanged();
        }
        if (other.hasRequired()) {
          setRequired(other.getRequired());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIdent()) {
          
          return false;
        }
        if (!hasFieldName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string ident = 1;
      private java.lang.Object ident_ = "";
      /**
       * <code>required string ident = 1;</code>
       */
      public boolean hasIdent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ident = 1;</code>
       */
      public java.lang.String getIdent() {
        java.lang.Object ref = ident_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ident_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ident = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdentBytes() {
        java.lang.Object ref = ident_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ident_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ident = 1;</code>
       */
      public Builder setIdent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ident_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ident = 1;</code>
       */
      public Builder clearIdent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ident_ = getDefaultInstance().getIdent();
        onChanged();
        return this;
      }
      /**
       * <code>required string ident = 1;</code>
       */
      public Builder setIdentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ident_ = value;
        onChanged();
        return this;
      }

      // required string fieldName = 2;
      private java.lang.Object fieldName_ = "";
      /**
       * <code>required string fieldName = 2;</code>
       */
      public boolean hasFieldName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string fieldName = 2;</code>
       */
      public java.lang.String getFieldName() {
        java.lang.Object ref = fieldName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fieldName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fieldName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFieldNameBytes() {
        java.lang.Object ref = fieldName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fieldName = 2;</code>
       */
      public Builder setFieldName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fieldName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fieldName = 2;</code>
       */
      public Builder clearFieldName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fieldName_ = getDefaultInstance().getFieldName();
        onChanged();
        return this;
      }
      /**
       * <code>required string fieldName = 2;</code>
       */
      public Builder setFieldNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fieldName_ = value;
        onChanged();
        return this;
      }

      // optional bool required = 3;
      private boolean required_ ;
      /**
       * <code>optional bool required = 3;</code>
       */
      public boolean hasRequired() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool required = 3;</code>
       */
      public boolean getRequired() {
        return required_;
      }
      /**
       * <code>optional bool required = 3;</code>
       */
      public Builder setRequired(boolean value) {
        bitField0_ |= 0x00000004;
        required_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool required = 3;</code>
       */
      public Builder clearRequired() {
        bitField0_ = (bitField0_ & ~0x00000004);
        required_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bowerbird.ItemField)
    }

    static {
      defaultInstance = new ItemField(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bowerbird.ItemField)
  }

  public interface RegexFieldOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string ident = 1;
    /**
     * <code>required string ident = 1;</code>
     */
    boolean hasIdent();
    /**
     * <code>required string ident = 1;</code>
     */
    java.lang.String getIdent();
    /**
     * <code>required string ident = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdentBytes();

    // required .bowerbird.RegexField.RegexFieldType type = 2;
    /**
     * <code>required .bowerbird.RegexField.RegexFieldType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .bowerbird.RegexField.RegexFieldType type = 2;</code>
     */
    bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType getType();

    // required .bowerbird.ItemField field = 3;
    /**
     * <code>required .bowerbird.ItemField field = 3;</code>
     */
    boolean hasField();
    /**
     * <code>required .bowerbird.ItemField field = 3;</code>
     */
    bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField getField();
    /**
     * <code>required .bowerbird.ItemField field = 3;</code>
     */
    bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemFieldOrBuilder getFieldOrBuilder();

    // optional string staticText = 4;
    /**
     * <code>optional string staticText = 4;</code>
     */
    boolean hasStaticText();
    /**
     * <code>optional string staticText = 4;</code>
     */
    java.lang.String getStaticText();
    /**
     * <code>optional string staticText = 4;</code>
     */
    com.google.protobuf.ByteString
        getStaticTextBytes();

    // optional string delim = 5;
    /**
     * <code>optional string delim = 5;</code>
     */
    boolean hasDelim();
    /**
     * <code>optional string delim = 5;</code>
     */
    java.lang.String getDelim();
    /**
     * <code>optional string delim = 5;</code>
     */
    com.google.protobuf.ByteString
        getDelimBytes();

    // repeated string terms = 6;
    /**
     * <code>repeated string terms = 6;</code>
     */
    java.util.List<java.lang.String>
    getTermsList();
    /**
     * <code>repeated string terms = 6;</code>
     */
    int getTermsCount();
    /**
     * <code>repeated string terms = 6;</code>
     */
    java.lang.String getTerms(int index);
    /**
     * <code>repeated string terms = 6;</code>
     */
    com.google.protobuf.ByteString
        getTermsBytes(int index);
  }
  /**
   * Protobuf type {@code bowerbird.RegexField}
   */
  public static final class RegexField extends
      com.google.protobuf.GeneratedMessage
      implements RegexFieldOrBuilder {
    // Use RegexField.newBuilder() to construct.
    private RegexField(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RegexField(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RegexField defaultInstance;
    public static RegexField getDefaultInstance() {
      return defaultInstance;
    }

    public RegexField getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RegexField(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              ident_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType value = bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = field_.toBuilder();
              }
              field_ = input.readMessage(bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(field_);
                field_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              staticText_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              delim_ = input.readBytes();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                terms_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              terms_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          terms_ = new com.google.protobuf.UnmodifiableLazyStringList(terms_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bowerbird.gpb.BowerbirdMessageProtocolGPB.internal_static_bowerbird_RegexField_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bowerbird.gpb.BowerbirdMessageProtocolGPB.internal_static_bowerbird_RegexField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.class, bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.Builder.class);
    }

    public static com.google.protobuf.Parser<RegexField> PARSER =
        new com.google.protobuf.AbstractParser<RegexField>() {
      public RegexField parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegexField(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RegexField> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code bowerbird.RegexField.RegexFieldType}
     */
    public enum RegexFieldType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0, 0),
      /**
       * <code>STATIC = 1;</code>
       */
      STATIC(1, 1),
      /**
       * <code>STANDARD = 2;</code>
       */
      STANDARD(2, 2),
      /**
       * <code>MULTIPLE = 3;</code>
       */
      MULTIPLE(3, 3),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>STATIC = 1;</code>
       */
      public static final int STATIC_VALUE = 1;
      /**
       * <code>STANDARD = 2;</code>
       */
      public static final int STANDARD_VALUE = 2;
      /**
       * <code>MULTIPLE = 3;</code>
       */
      public static final int MULTIPLE_VALUE = 3;


      public final int getNumber() { return value; }

      public static RegexFieldType valueOf(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return STATIC;
          case 2: return STANDARD;
          case 3: return MULTIPLE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RegexFieldType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RegexFieldType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RegexFieldType>() {
              public RegexFieldType findValueByNumber(int number) {
                return RegexFieldType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.getDescriptor().getEnumTypes().get(0);
      }

      private static final RegexFieldType[] VALUES = values();

      public static RegexFieldType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RegexFieldType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:bowerbird.RegexField.RegexFieldType)
    }

    private int bitField0_;
    // required string ident = 1;
    public static final int IDENT_FIELD_NUMBER = 1;
    private java.lang.Object ident_;
    /**
     * <code>required string ident = 1;</code>
     */
    public boolean hasIdent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ident = 1;</code>
     */
    public java.lang.String getIdent() {
      java.lang.Object ref = ident_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ident_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ident = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdentBytes() {
      java.lang.Object ref = ident_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ident_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .bowerbird.RegexField.RegexFieldType type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType type_;
    /**
     * <code>required .bowerbird.RegexField.RegexFieldType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .bowerbird.RegexField.RegexFieldType type = 2;</code>
     */
    public bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType getType() {
      return type_;
    }

    // required .bowerbird.ItemField field = 3;
    public static final int FIELD_FIELD_NUMBER = 3;
    private bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField field_;
    /**
     * <code>required .bowerbird.ItemField field = 3;</code>
     */
    public boolean hasField() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .bowerbird.ItemField field = 3;</code>
     */
    public bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField getField() {
      return field_;
    }
    /**
     * <code>required .bowerbird.ItemField field = 3;</code>
     */
    public bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemFieldOrBuilder getFieldOrBuilder() {
      return field_;
    }

    // optional string staticText = 4;
    public static final int STATICTEXT_FIELD_NUMBER = 4;
    private java.lang.Object staticText_;
    /**
     * <code>optional string staticText = 4;</code>
     */
    public boolean hasStaticText() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string staticText = 4;</code>
     */
    public java.lang.String getStaticText() {
      java.lang.Object ref = staticText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          staticText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string staticText = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStaticTextBytes() {
      java.lang.Object ref = staticText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staticText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string delim = 5;
    public static final int DELIM_FIELD_NUMBER = 5;
    private java.lang.Object delim_;
    /**
     * <code>optional string delim = 5;</code>
     */
    public boolean hasDelim() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string delim = 5;</code>
     */
    public java.lang.String getDelim() {
      java.lang.Object ref = delim_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          delim_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string delim = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDelimBytes() {
      java.lang.Object ref = delim_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        delim_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string terms = 6;
    public static final int TERMS_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList terms_;
    /**
     * <code>repeated string terms = 6;</code>
     */
    public java.util.List<java.lang.String>
        getTermsList() {
      return terms_;
    }
    /**
     * <code>repeated string terms = 6;</code>
     */
    public int getTermsCount() {
      return terms_.size();
    }
    /**
     * <code>repeated string terms = 6;</code>
     */
    public java.lang.String getTerms(int index) {
      return terms_.get(index);
    }
    /**
     * <code>repeated string terms = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTermsBytes(int index) {
      return terms_.getByteString(index);
    }

    private void initFields() {
      ident_ = "";
      type_ = bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType.UNKNOWN;
      field_ = bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.getDefaultInstance();
      staticText_ = "";
      delim_ = "";
      terms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIdent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasField()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getField().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, field_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getStaticTextBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDelimBytes());
      }
      for (int i = 0; i < terms_.size(); i++) {
        output.writeBytes(6, terms_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, field_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getStaticTextBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDelimBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < terms_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(terms_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTermsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bowerbird.RegexField}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexFieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bowerbird.gpb.BowerbirdMessageProtocolGPB.internal_static_bowerbird_RegexField_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bowerbird.gpb.BowerbirdMessageProtocolGPB.internal_static_bowerbird_RegexField_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.class, bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.Builder.class);
      }

      // Construct using bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFieldFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ident_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (fieldBuilder_ == null) {
          field_ = bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.getDefaultInstance();
        } else {
          fieldBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        staticText_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        delim_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        terms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bowerbird.gpb.BowerbirdMessageProtocolGPB.internal_static_bowerbird_RegexField_descriptor;
      }

      public bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField getDefaultInstanceForType() {
        return bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.getDefaultInstance();
      }

      public bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField build() {
        bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField buildPartial() {
        bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField result = new bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ident_ = ident_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (fieldBuilder_ == null) {
          result.field_ = field_;
        } else {
          result.field_ = fieldBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.staticText_ = staticText_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.delim_ = delim_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          terms_ = new com.google.protobuf.UnmodifiableLazyStringList(
              terms_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.terms_ = terms_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField) {
          return mergeFrom((bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField other) {
        if (other == bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.getDefaultInstance()) return this;
        if (other.hasIdent()) {
          bitField0_ |= 0x00000001;
          ident_ = other.ident_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasField()) {
          mergeField(other.getField());
        }
        if (other.hasStaticText()) {
          bitField0_ |= 0x00000008;
          staticText_ = other.staticText_;
          onChanged();
        }
        if (other.hasDelim()) {
          bitField0_ |= 0x00000010;
          delim_ = other.delim_;
          onChanged();
        }
        if (!other.terms_.isEmpty()) {
          if (terms_.isEmpty()) {
            terms_ = other.terms_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureTermsIsMutable();
            terms_.addAll(other.terms_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIdent()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasField()) {
          
          return false;
        }
        if (!getField().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string ident = 1;
      private java.lang.Object ident_ = "";
      /**
       * <code>required string ident = 1;</code>
       */
      public boolean hasIdent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ident = 1;</code>
       */
      public java.lang.String getIdent() {
        java.lang.Object ref = ident_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ident_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ident = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdentBytes() {
        java.lang.Object ref = ident_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ident_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ident = 1;</code>
       */
      public Builder setIdent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ident_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ident = 1;</code>
       */
      public Builder clearIdent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ident_ = getDefaultInstance().getIdent();
        onChanged();
        return this;
      }
      /**
       * <code>required string ident = 1;</code>
       */
      public Builder setIdentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ident_ = value;
        onChanged();
        return this;
      }

      // required .bowerbird.RegexField.RegexFieldType type = 2;
      private bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType type_ = bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType.UNKNOWN;
      /**
       * <code>required .bowerbird.RegexField.RegexFieldType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .bowerbird.RegexField.RegexFieldType type = 2;</code>
       */
      public bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType getType() {
        return type_;
      }
      /**
       * <code>required .bowerbird.RegexField.RegexFieldType type = 2;</code>
       */
      public Builder setType(bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .bowerbird.RegexField.RegexFieldType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = bowerbird.gpb.BowerbirdMessageProtocolGPB.RegexField.RegexFieldType.UNKNOWN;
        onChanged();
        return this;
      }

      // required .bowerbird.ItemField field = 3;
      private bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField field_ = bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField, bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.Builder, bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemFieldOrBuilder> fieldBuilder_;
      /**
       * <code>required .bowerbird.ItemField field = 3;</code>
       */
      public boolean hasField() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .bowerbird.ItemField field = 3;</code>
       */
      public bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField getField() {
        if (fieldBuilder_ == null) {
          return field_;
        } else {
          return fieldBuilder_.getMessage();
        }
      }
      /**
       * <code>required .bowerbird.ItemField field = 3;</code>
       */
      public Builder setField(bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField value) {
        if (fieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          field_ = value;
          onChanged();
        } else {
          fieldBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .bowerbird.ItemField field = 3;</code>
       */
      public Builder setField(
          bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.Builder builderForValue) {
        if (fieldBuilder_ == null) {
          field_ = builderForValue.build();
          onChanged();
        } else {
          fieldBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .bowerbird.ItemField field = 3;</code>
       */
      public Builder mergeField(bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField value) {
        if (fieldBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              field_ != bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.getDefaultInstance()) {
            field_ =
              bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.newBuilder(field_).mergeFrom(value).buildPartial();
          } else {
            field_ = value;
          }
          onChanged();
        } else {
          fieldBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .bowerbird.ItemField field = 3;</code>
       */
      public Builder clearField() {
        if (fieldBuilder_ == null) {
          field_ = bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.getDefaultInstance();
          onChanged();
        } else {
          fieldBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .bowerbird.ItemField field = 3;</code>
       */
      public bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.Builder getFieldBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFieldFieldBuilder().getBuilder();
      }
      /**
       * <code>required .bowerbird.ItemField field = 3;</code>
       */
      public bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemFieldOrBuilder getFieldOrBuilder() {
        if (fieldBuilder_ != null) {
          return fieldBuilder_.getMessageOrBuilder();
        } else {
          return field_;
        }
      }
      /**
       * <code>required .bowerbird.ItemField field = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField, bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.Builder, bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemFieldOrBuilder> 
          getFieldFieldBuilder() {
        if (fieldBuilder_ == null) {
          fieldBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField, bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemField.Builder, bowerbird.gpb.BowerbirdMessageProtocolGPB.ItemFieldOrBuilder>(
                  field_,
                  getParentForChildren(),
                  isClean());
          field_ = null;
        }
        return fieldBuilder_;
      }

      // optional string staticText = 4;
      private java.lang.Object staticText_ = "";
      /**
       * <code>optional string staticText = 4;</code>
       */
      public boolean hasStaticText() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string staticText = 4;</code>
       */
      public java.lang.String getStaticText() {
        java.lang.Object ref = staticText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          staticText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string staticText = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStaticTextBytes() {
        java.lang.Object ref = staticText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          staticText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string staticText = 4;</code>
       */
      public Builder setStaticText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        staticText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string staticText = 4;</code>
       */
      public Builder clearStaticText() {
        bitField0_ = (bitField0_ & ~0x00000008);
        staticText_ = getDefaultInstance().getStaticText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string staticText = 4;</code>
       */
      public Builder setStaticTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        staticText_ = value;
        onChanged();
        return this;
      }

      // optional string delim = 5;
      private java.lang.Object delim_ = "";
      /**
       * <code>optional string delim = 5;</code>
       */
      public boolean hasDelim() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string delim = 5;</code>
       */
      public java.lang.String getDelim() {
        java.lang.Object ref = delim_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          delim_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string delim = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDelimBytes() {
        java.lang.Object ref = delim_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          delim_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string delim = 5;</code>
       */
      public Builder setDelim(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        delim_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string delim = 5;</code>
       */
      public Builder clearDelim() {
        bitField0_ = (bitField0_ & ~0x00000010);
        delim_ = getDefaultInstance().getDelim();
        onChanged();
        return this;
      }
      /**
       * <code>optional string delim = 5;</code>
       */
      public Builder setDelimBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        delim_ = value;
        onChanged();
        return this;
      }

      // repeated string terms = 6;
      private com.google.protobuf.LazyStringList terms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTermsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          terms_ = new com.google.protobuf.LazyStringArrayList(terms_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string terms = 6;</code>
       */
      public java.util.List<java.lang.String>
          getTermsList() {
        return java.util.Collections.unmodifiableList(terms_);
      }
      /**
       * <code>repeated string terms = 6;</code>
       */
      public int getTermsCount() {
        return terms_.size();
      }
      /**
       * <code>repeated string terms = 6;</code>
       */
      public java.lang.String getTerms(int index) {
        return terms_.get(index);
      }
      /**
       * <code>repeated string terms = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTermsBytes(int index) {
        return terms_.getByteString(index);
      }
      /**
       * <code>repeated string terms = 6;</code>
       */
      public Builder setTerms(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTermsIsMutable();
        terms_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string terms = 6;</code>
       */
      public Builder addTerms(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTermsIsMutable();
        terms_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string terms = 6;</code>
       */
      public Builder addAllTerms(
          java.lang.Iterable<java.lang.String> values) {
        ensureTermsIsMutable();
        super.addAll(values, terms_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string terms = 6;</code>
       */
      public Builder clearTerms() {
        terms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string terms = 6;</code>
       */
      public Builder addTermsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTermsIsMutable();
        terms_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bowerbird.RegexField)
    }

    static {
      defaultInstance = new RegexField(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bowerbird.RegexField)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bowerbird_ItemField_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bowerbird_ItemField_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bowerbird_RegexField_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bowerbird_RegexField_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036External/proto/Bowerbird.proto\022\tbowerb" +
      "ird\"?\n\tItemField\022\r\n\005ident\030\001 \002(\t\022\021\n\tfield" +
      "Name\030\002 \002(\t\022\020\n\010required\030\003 \001(\010\"\355\001\n\nRegexFi" +
      "eld\022\r\n\005ident\030\001 \002(\t\0222\n\004type\030\002 \002(\0162$.bower" +
      "bird.RegexField.RegexFieldType\022#\n\005field\030" +
      "\003 \002(\0132\024.bowerbird.ItemField\022\022\n\nstaticTex" +
      "t\030\004 \001(\t\022\r\n\005delim\030\005 \001(\t\022\r\n\005terms\030\006 \003(\t\"E\n" +
      "\016RegexFieldType\022\013\n\007UNKNOWN\020\000\022\n\n\006STATIC\020\001" +
      "\022\014\n\010STANDARD\020\002\022\014\n\010MULTIPLE\020\003B,\n\rbowerbir" +
      "d.gpbB\033BowerbirdMessageProtocolGPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_bowerbird_ItemField_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_bowerbird_ItemField_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bowerbird_ItemField_descriptor,
              new java.lang.String[] { "Ident", "FieldName", "Required", });
          internal_static_bowerbird_RegexField_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_bowerbird_RegexField_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bowerbird_RegexField_descriptor,
              new java.lang.String[] { "Ident", "Type", "Field", "StaticText", "Delim", "Terms", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
